info:
 author: Dhiman
 organization: CTS
 
---
spring:
 profiles: dev
 
my:
 custom:
  environment: Developement
  
---

spring:
 profiles: prod
 
my:
 custom:
  environment: Production